{{- if and (not .Values.auth.existingSecret) .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.authSecretName" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
