# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-27T14:32:17+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class ApiKeyRole(Enum):
    viewer = 'viewer'
    operator = 'operator'
    admin = 'admin'


class VerifyTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token: str


class VerifyTokenResponse(BaseModel):
    valid: bool
    role: ApiKeyRole | None = None


class Status(Enum):
    ok = 'ok'


class Sessions(BaseModel):
    active: int | None = None
    total: int | None = None


class HealthResponse(BaseModel):
    status: Status | None = None
    version: str | None = Field(None, examples=['0.6.0-preview'])
    uptime: int | None = Field(None, description='Seconds since server start')
    sessions: Sessions | None = None


class ApiKey(BaseModel):
    id: str | None = None
    name: str | None = None
    keyId: str | None = Field(None, description='First 8 characters of the key hash')
    createdAt: int | None = None
    expiresAt: int | None = None
    lastUsedAt: int | None = None


class ApiKeyCreated(BaseModel):
    id: str | None = None
    name: str | None = None
    key: str | None = Field(
        None, description='Full plaintext key — shown ONLY here, never again'
    )
    keyId: str | None = None
    createdAt: int | None = None


class HandshakeResponse(BaseModel):
    protocolVersion: str | None = None
    serverCapabilities: list[str] | None = None
    negotiatedCapabilities: list[str] | None = None
    warnings: list[str] | None = None
    compatible: bool | None = None


class PermissionMode(Enum):
    default = 'default'
    bypassPermissions = 'bypassPermissions'
    plan = 'plan'
    acceptEdits = 'acceptEdits'
    dontAsk = 'dontAsk'
    auto = 'auto'


class CreateSessionRequest(BaseModel):
    name: str | None = Field(
        None, description='Human-readable session name', examples=['feature-auth']
    )
    workDir: str = Field(
        ...,
        description='Working directory for Claude Code',
        examples=['/home/user/my-project'],
    )
    prompt: str | None = Field(
        None, description='Initial prompt to send to Claude Code'
    )
    permissionMode: PermissionMode | None = 'default'
    autoApprove: bool | None = False
    env: dict[str, str] | None = Field(
        None, description='Environment variables to inject into the session'
    )
    claudeCommand: constr(max_length=10000) | None = Field(
        None, description='Custom Claude Code command/flags'
    )
    maxSessionAgeMs: int | None = Field(
        None, description='Maximum session lifetime in milliseconds'
    )
    stallThresholdMs: int | None = Field(
        None, description='Stall detection threshold override'
    )


class PromptDelivery(BaseModel):
    delivered: bool | None = None
    attempts: int | None = None


class SessionCreated(BaseModel):
    id: str | None = None
    name: str | None = None
    status: str | None = Field(None, examples=['working'])
    workDir: str | None = None
    reused: bool | None = Field(None, examples=[False])
    promptDelivery: PromptDelivery | None = None


class SessionReused(SessionCreated):
    reused: bool | None = Field(None, examples=[True])


class Status1(Enum):
    idle = 'idle'
    working = 'working'
    compacting = 'compacting'
    context_warning = 'context_warning'
    waiting_for_input = 'waiting_for_input'
    permission_prompt = 'permission_prompt'
    plan_mode = 'plan_mode'
    ask_question = 'ask_question'
    bash_approval = 'bash_approval'
    settings = 'settings'
    error = 'error'
    unknown = 'unknown'


class SessionInfo(BaseModel):
    id: str | None = None
    windowId: str | None = None
    windowName: str | None = None
    workDir: str | None = None
    claudeSessionId: str | None = None
    jsonlPath: str | None = None
    byteOffset: int | None = None
    monitorOffset: int | None = None
    status: Status1 | None = None
    createdAt: int | None = None
    lastActivity: int | None = None
    stallThresholdMs: int | None = None
    permissionStallMs: int | None = None
    permissionMode: str | None = None
    settingsPatched: bool | None = None
    hookSettingsFile: str | None = None
    hookSecret: str | None = None
    lastHookAt: int | None = None
    activeSubagents: list[str] | None = None
    permissionPromptAt: int | None = None
    permissionRespondedAt: int | None = None
    lastHookReceivedAt: int | None = None
    lastHookEventAt: int | None = None
    model: str | None = None
    lastDeadAt: int | None = None
    ccPid: int | None = None
    parentId: str | None = None
    children: list[str] | None = None
    permissionPolicy: list[dict[str, Any]] | None = None
    permissionProfile: dict[str, Any] | None = None
    prd: str | None = None
    ownerKeyId: str | None = None


class SessionHealth(BaseModel):
    alive: bool | None = None
    windowExists: bool | None = None
    paneState: str | None = None
    lastSeen: int | None = None
    suggestion: str | None = None


class TokenUsage(BaseModel):
    inputTokens: int | None = None
    outputTokens: int | None = None
    cacheCreation: int | None = None
    cacheRead: int | None = None
    estimatedCostUsd: float | None = None


class SessionMetrics(BaseModel):
    messages: int | None = None
    toolCalls: int | None = None
    approvals: int | None = None
    autoApprovals: int | None = None
    statusChanges: list[dict[str, Any]] | None = None
    tokenUsage: TokenUsage | None = None


class Role(Enum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'


class TranscriptEntry(BaseModel):
    id: int | None = None
    role: Role | None = None
    content: str | None = None
    timestamp: int | None = None
    toolCalls: list[dict[str, Any]] | None = None


class VerificationResult(BaseModel):
    success: bool | None = None
    output: str | None = None
    durationMs: int | None = None
    exitCode: int | None = None


class SessionTemplate(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    prompt: str | None = None
    workDir: str | None = None
    permissionMode: str | None = None
    tags: list[str] | None = None
    createdAt: int | None = None


class CreateTemplateRequest(BaseModel):
    name: str
    description: str | None = None
    prompt: str
    workDir: str | None = None
    permissionMode: PermissionMode | None = 'default'
    tags: list[str] | None = None


class Stage(BaseModel):
    id: str | None = None
    prompt: str | None = None
    workDir: str | None = None
    permissionMode: str | None = None
    dependencies: list[str] | None = None
    maxSessionAgeMs: int | None = None


class CreatePipelineRequest(BaseModel):
    name: str | None = None
    stages: list[Stage] = Field(..., max_length=50)


class GlobalMetrics(BaseModel):
    sessionsCreated: int | None = None
    sessionsCompleted: int | None = None
    sessionsFailed: int | None = None
    totalMessages: int | None = None
    totalToolCalls: int | None = None
    autoApprovals: int | None = None
    webhooksSent: int | None = None
    webhooksFailed: int | None = None
    screenshotsTaken: int | None = None
    pipelinesCreated: int | None = None
    batchesCreated: int | None = None
    promptsSent: int | None = None
    promptsDelivered: int | None = None
    promptsFailed: int | None = None
    avgDurationSec: float | None = None


class SessionStatusFilter(Enum):
    all = 'all'
    idle = 'idle'
    working = 'working'
    compacting = 'compacting'
    context_warning = 'context_warning'
    waiting_for_input = 'waiting_for_input'
    permission_prompt = 'permission_prompt'
    plan_mode = 'plan_mode'
    ask_question = 'ask_question'
    bash_approval = 'bash_approval'
    settings = 'settings'
    error = 'error'
    unknown = 'unknown'
