#!/usr/bin/env bash
# install-systemd.sh — Install Aegis systemd unit with correct paths
#
# Usage:
#   sudo ./scripts/install-systemd.sh                     # defaults: /opt/aegis, user=aegis
#   sudo ./scripts/install-systemd.sh /home/user/aegis user  # custom path + user
#
# What it does:
#   1. Generates aegis.service from template with correct WorkingDirectory/User
#   2. Generates aegis-pre-start.sh with build step + cleanup
#   3. Installs both to the correct system locations
#   4. Reloads systemd daemon
#
# Options:
#   --skip-build    Omit the npm run build step from ExecStartPre
#   --dry-run       Print what would be installed, don't write anything
#
# Fixes: #3486 — keeps deployed systemd unit in sync with repo template

set -euo pipefail

SKIP_BUILD=false
DRY_RUN=false
AEGIS_DIR="/opt/aegis"
AEGIS_USER="aegis"

for arg in "$@"; do
  case "$arg" in
    --skip-build) SKIP_BUILD=true ;;
    --dry-run) DRY_RUN=true ;;
    *)
      if [ -z "${AEGIS_DIR_SET:-}" ]; then
        AEGIS_DIR="$arg"
        AEGIS_DIR_SET=1
      elif [ -z "${AEGIS_USER_SET:-}" ]; then
        AEGIS_USER="$arg"
        AEGIS_USER_SET=1
      fi
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=== Aegis systemd installer ==="
echo "  Aegis dir:  $AEGIS_DIR"
echo "  Aegis user: $AEGIS_USER"
echo "  Skip build: $SKIP_BUILD"
echo "  Dry run:    $DRY_RUN"
echo ""

# --- Generate aegis-pre-start.sh ---
PRE_START_SCRIPT=$(cat << PRESTART
#!/bin/bash
# aegis-pre-start.sh — ExecStartPre for Aegis service
# Rebuilds dist/ and cleans stale processes/sockets before start.
# Generated by install-systemd.sh from repo template.

set -euo pipefail

AEGIS_DIR="${AEGIS_DIR}"
AEGIS_PORT="\${AEGIS_PORT:-9100}"
SOCKET_DIR="/tmp/tmux-\$(id -u)"

# 0. Rebuild dist/ before starting (prevents stale code after merges)
if [ "${SKIP_BUILD}" != "true" ]; then
  echo "ExecStartPre: rebuilding dist/..."
  cd "\$AEGIS_DIR"
  if npm run build 2>&1 | while read -r line; do echo "build: \$line"; done; then
    echo "ExecStartPre: build succeeded"
  else
    echo "ExecStartPre: build FAILED — continuing with existing dist/"
  fi
fi

# 1. Kill any process holding our port (stale server from previous crash)
PORT_PID=\$(ss -tlnp "sport = :\${AEGIS_PORT}" 2>/dev/null | grep -oP 'pid=\\K\\d+' | head -1)
if [ -n "\$PORT_PID" ]; then
  echo "ExecStartPre: killing stale process \$PORT_PID on port \$AEGIS_PORT"
  kill -9 "\$PORT_PID" 2>/dev/null
  sleep 1
fi

# 2. Clean stale PID files
for pidfile in "\$HOME/.aegis/aegis.pid"; do
  if [ -f "\$pidfile" ]; then
    OLD_PID=\$(cat "\$pidfile" 2>/dev/null)
    if [ -n "\$OLD_PID" ] && ! kill -0 "\$OLD_PID" 2>/dev/null; then
      echo "ExecStartPre: removing stale PID file \$pidfile (PID \$OLD_PID dead)"
      rm -f "\$pidfile"
    fi
  fi
done

# 3. Clean stale tmux sockets
if [ -d "\$SOCKET_DIR" ]; then
  for sock in "\$SOCKET_DIR"/aegis-*; do
    [ -e "\$sock" ] || continue
    SOCK_PID=\$(basename "\$sock" | sed 's/aegis-//')
    if ! kill -0 "\$SOCK_PID" 2>/dev/null; then
      echo "ExecStartPre: removing stale socket \$sock"
      rm -f "\$sock"
    fi
  done
fi

echo "ExecStartPre: complete"
PRESTART
)

# --- Generate aegis.service ---
UNIT_FILE=$(cat << UNIT
[Unit]
Description=Aegis Server — Claude Code orchestration
Documentation=https://docs.aegis.ai
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${AEGIS_USER}
Group=${AEGIS_USER}
WorkingDirectory=${AEGIS_DIR}
ExecStartPre=/usr/local/bin/aegis-pre-start.sh
ExecStart=/usr/bin/node dist/server.js
ExecStartPost=/bin/bash -c 'for i in \$(seq 1 15); do curl -sf http://localhost:\${AEGIS_PORT:-9100}/health && exit 0; sleep 1; done; echo "WARN: health endpoint not responding after 15s"'
Restart=on-failure
RestartSec=5
StartLimitIntervalSec=300
StartLimitBurst=10
Environment=AEGIS_PORT=9100
EnvironmentFile=-/etc/aegis/aegis.env
StandardOutput=journal
StandardError=journal
SyslogIdentifier=aegis

[Install]
WantedBy=multi-user.target
UNIT
)

# --- Install ---
if [ "$DRY_RUN" = "true" ]; then
  echo "--- aegis-pre-start.sh (would install to /usr/local/bin/) ---"
  echo "$PRE_START_SCRIPT"
  echo ""
  echo "--- aegis.service (would install to /etc/systemd/system/) ---"
  echo "$UNIT_FILE"
  echo ""
  echo "To apply: sudo $0 $AEGIS_DIR $AEGIS_USER"
  exit 0
fi

echo "Installing aegis-pre-start.sh → /usr/local/bin/"
echo "$PRE_START_SCRIPT" > /usr/local/bin/aegis-pre-start.sh
chmod +x /usr/local/bin/aegis-pre-start.sh

echo "Installing aegis.service → /etc/systemd/system/"
echo "$UNIT_FILE" > /etc/systemd/system/aegis.service

echo "Reloading systemd daemon..."
systemctl daemon-reload

echo ""
echo "✅ Done. Run 'systemctl restart aegis' to apply."
echo "   Verify: systemctl cat aegis"
