apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis.headlessServiceName" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
  selector:
    {{- include "aegis.selectorLabels" . | nindent 4 }}
