apiVersion: v1
entries:
  aegis:
  - apiVersion: v2
    appVersion: 0.6.5-preview.3
    created: "2026-05-02T05:00:19.919704208Z"
    description: Deploy Aegis on Kubernetes or k3s with persistent session state.
    digest: efa4fe4a3149b4b937ff30d1a5e9f9d62317f1bd5def0b20faad9c30ad8775ff
    home: https://github.com/OneStepAt4time/aegis
    keywords:
    - aegis
    - claude-code
    - mcp
    - tmux
    maintainers:
    - name: OneStepAt4time
      url: https://github.com/OneStepAt4time
    name: aegis
    sources:
    - https://github.com/OneStepAt4time/aegis
    type: application
    urls:
    - https://onestepat4time.github.io/aegis/helm/aegis-0.6.5-preview.3.tgz
    version: 0.6.5-preview.3
generated: "2026-05-02T05:00:19.918992293Z"
