/**
 * openapi.ts — OpenAPI 3.1 document generation from Zod schemas.
 *
 * Uses Zod 4's native toJSONSchema (zod/v4/core) for schema conversion.
 * Route modules register their endpoints via registerOpenApiPath().
 * The final OpenAPI 3.1 document is generated by generateOpenApiDocument().
 *
 * Issue #1909.
 */

import { z } from 'zod';
import { toJSONSchema } from 'zod/v4/core';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

// ── Types ──────────────────────────────────────────────────────────

export type HttpMethod = 'get' | 'post' | 'put' | 'delete' | 'patch';

export interface OpenApiPathParams {
  method: HttpMethod;
  path: string;
  operationId?: string;
  summary?: string;
  description?: string;
  tags?: string[];
  deprecated?: boolean;
  requestBody?: {
    description?: string;
    required?: boolean;
    content: Record<string, {
      schema: z.ZodType;
    }>;
  };
  parameters?: Array<{
    name: string;
    in: 'query' | 'path' | 'header';
    required?: boolean;
    description?: string;
    schema: z.ZodType;
  }>;
  responses: Record<string, {
    description: string;
    content?: Record<string, {
      schema: z.ZodType;
    }>;
  }>;
}

// ── Internal storage ───────────────────────────────────────────────

interface StoredPath {
  spec: OpenApiPathParams;
}

const registeredPaths: StoredPath[] = [];

// ── Public API ─────────────────────────────────────────────────────

/** Register a route's OpenAPI descriptor. Called from route modules. */
export function registerOpenApiPath(spec: OpenApiPathParams): void {
  registeredPaths.push({ spec });
}

/** Clear all registered paths (useful for testing). */
export function clearOpenApiPaths(): void {
  registeredPaths.length = 0;
}

/**
 * Convert a Zod schema to a JSON Schema object suitable for OpenAPI 3.1.
 * Strips the `$schema` keyword (not allowed inside OpenAPI schema objects).
 */
export function zodToJsonSchema(schema: z.ZodType): Record<string, unknown> {
  const jsonSchema = toJSONSchema(schema) as Record<string, unknown>;
  // OpenAPI 3.1 schema objects MUST NOT contain $schema
  const { $schema: _, ...rest } = jsonSchema;
  return rest;
}

/** Generate the complete OpenAPI 3.1 document from all registered routes. */
export function generateOpenApiDocument(info?: { title?: string; version?: string }): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  const componentSchemas: Record<string, Record<string, unknown>> = {};

  for (const { spec } of registeredPaths) {
    if (!paths[spec.path]) {
      paths[spec.path] = {};
    }

    const operation: Record<string, unknown> = {};

    if (spec.summary) operation.summary = spec.summary;
    if (spec.description) operation.description = spec.description;
    operation.operationId = spec.operationId ?? getOperationId(spec.method, spec.path);
    if (spec.tags) operation.tags = spec.tags;
    if (spec.deprecated) operation.deprecated = true;

    // Parameters
    if (spec.parameters && spec.parameters.length > 0) {
      operation.parameters = spec.parameters.map((p) => ({
        name: p.name,
        in: p.in,
        required: p.required,
        ...(p.description && { description: p.description }),
        schema: zodToJsonSchema(p.schema),
      }));
    }

    // Request body
    if (spec.requestBody) {
      const content: Record<string, unknown> = {};
      for (const [mediaType, entry] of Object.entries(spec.requestBody.content)) {
        content[mediaType] = {
          schema: zodToJsonSchema(entry.schema),
        };
      }
      operation.requestBody = {
        description: spec.requestBody.description,
        required: spec.requestBody.required ?? true,
        content,
      };
    }

    // Responses
    const responses: Record<string, unknown> = {};
    for (const [status, resp] of Object.entries(spec.responses)) {
      const responseObj: Record<string, unknown> = {
        description: resp.description,
      };
      if (resp.content) {
        const content: Record<string, unknown> = {};
        for (const [mediaType, entry] of Object.entries(resp.content)) {
          content[mediaType] = {
            schema: zodToJsonSchema(entry.schema),
          };
        }
        responseObj.content = content;
      }
      responses[status] = responseObj;
    }
    operation.responses = responses;

    paths[spec.path][spec.method] = operation;
  }

  const pkg = readPackageInfo();

  return {
    openapi: '3.1.0',
    info: {
      title: info?.title ?? pkg.name,
      version: info?.version ?? pkg.version,
      description: 'Orchestrate Claude Code sessions via API. Create, brief, monitor, refine, ship.',
    },
    servers: [
      { url: '/v1', description: 'API v1' },
    ],
    paths,
    ...(Object.keys(componentSchemas).length > 0 && {
      components: { schemas: componentSchemas },
    }),
  };
}

// ── Helpers ────────────────────────────────────────────────────────

interface PackageInfo {
  name: string;
  version: string;
}

let cachedPkg: PackageInfo | undefined;

function readPackageInfo(): PackageInfo {
  if (cachedPkg) return cachedPkg;
  try {
    const thisFile = fileURLToPath(import.meta.url);
    const pkgPath = new URL('../../package.json', `file://${thisFile}`);
    const data = JSON.parse(fs.readFileSync(fileURLToPath(pkgPath), 'utf-8'));
    cachedPkg = { name: data.name ?? '@onestepat4time/aegis', version: data.version ?? '0.0.0' };
    return cachedPkg;
  } catch {
    cachedPkg = { name: '@onestepat4time/aegis', version: '0.0.0' };
    return cachedPkg;
  }
}

function getOperationId(method: HttpMethod, path: string): string {
  return `${method}${path
    .split('/')
    .filter(Boolean)
    .map((part) => toPascalCase(part.replace(/[{}]/g, '')))
    .join('')}`;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// ── Error response schema helper ──────────────────────────────────

/** Standard error response schema used across Aegis routes. */
export const errorResponseSchema = {
  description: 'Error response',
  content: {
    'application/json': {
      schema: z.object({ error: z.string() }),
    },
  },
} as const satisfies { description: string; content: Record<string, { schema: z.ZodType }> };

/** Convenience: 400 validation error response. */
export function validationErrorResponse(description = 'Validation error') {
  return {
    description,
    content: {
      'application/json': {
        schema: z.object({ error: z.string(), details: z.array(z.any()).optional() }),
      },
    },
  };
}
